<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\PermissionRegistrar;

class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $rolePermissions = [
            'super_admin' => Permission::query()
                ->where('guard_name', 'web')
                ->pluck('name')
                ->all(),
            'owner' => [
                'analytics.view',
                'companies.view',
                'companies.update',
                'branches.view',
                'branches.create',
                'branches.update',
                'branches.delete',
                'users.view',
                'users.create',
                'users.update',
                'customers.view',
                'customers.create',
                'customers.update',
                'devices.view',
                'devices.create',
                'devices.update',
                'tickets.view',
                'tickets.create',
                'tickets.update',
                'tickets.assign',
                'tickets.close',
                'diagnostics.view',
                'diagnostics.create',
                'diagnostics.update',
                'diagnostics.start',
                'diagnostics.complete',
                'quotes.view',
                'quotes.create',
                'quotes.update',
                'repairs.view',
                'repairs.create',
                'repairs.update',
                'repairs.assign',
                'repairs.start',
                'repairs.complete',
                'invoices.view',
                'invoices.create',
                'invoices.update',
                'billings.view',
                'billings.create',
                'billings.update',
                'billings.mark-paid',
                'billings.mark-failed',
                'billings.cancel',
                'billings.refund',
                'payments.view',
                'payments.create',
                'products.view',
                'products.create',
                'products.update',
                'inventory.view',
                'inventory.create',
                'inventory.update',
                'inventory.approve',
                'inventory.complete',
                'inventory.cancel',
                'suppliers.view',
                'suppliers.create',
                'suppliers.update',
                'purchase-orders.view',
                'purchase-orders.create',
                'purchase-orders.update',
                'purchase-orders.approve',
                'goods-receipts.view',
                'goods-receipts.create',
                'goods-receipts.update',
                'purchase-orders.cancel',
                'dashboards.view',
                'dashboards.create',
                'dashboards.update',
                'dashboards.delete',
                'warranties.view',
                'warranties.create',
                'warranties.update',
                'warranties.delete',
                'warranties.claim',
                'warranties.expire',
                'warranties.void',
                'accounting.view',
                'accounting.create',
                'accounting.update',
                'accounting.delete',
                'accounting.post',
                'accounting.cancel',
                'ai.view',
                'ai.use',
                'reports.view',
                'reports.export',
            ],
            'administrator' => [
                'analytics.view',
                'branches.view',
                'branches.create',
                'branches.update',
                'users.view',
                'users.create',
                'users.update',
                'customers.view',
                'customers.create',
                'customers.update',
                'devices.view',
                'devices.create',
                'devices.update',
                'tickets.view',
                'tickets.create',
                'tickets.update',
                'tickets.assign',
                'diagnostics.view',
                'diagnostics.create',
                'diagnostics.update',
                'quotes.view',
                'quotes.create',
                'quotes.update',
                'repairs.view',
                'repairs.create',
                'repairs.update',
                'ai.view',
                'ai.use',
                'invoices.view',
                'billings.view',
                'payments.view',
                'dashboards.view',
                'warranties.view',
                'warranties.create',
                'warranties.update',
                'warranties.claim',
                'accounting.view',
                'reports.view',
                'reports.export',
            ],
            'manager' => [
                'analytics.view',
                'customers.view',
                'devices.view',
                'tickets.view',
                'tickets.update',
                'tickets.assign',
                'diagnostics.view',
                'diagnostics.update',
                'quotes.view',
                'quotes.create',
                'quotes.update',
                'repairs.view',
                'repairs.update',
                'warranties.view',
                'ai.view',
                'ai.use',
                'reports.view',
            ],
            'receptionist' => [
                'customers.view',
                'customers.create',
                'customers.update',
                'devices.view',
                'devices.create',
                'devices.update',
                'tickets.view',
                'tickets.create',
                'tickets.update',
                'quotes.view',
                'ai.view',
            ],
            'warehouse' => [
                'products.view',
                'products.create',
                'products.update',
                'inventory.view',
                'inventory.create',
                'inventory.update',
                'inventory.approve',
                'inventory.complete',
                'inventory.cancel',
                'suppliers.view',
                'suppliers.create',
                'suppliers.update',
                'purchase-orders.view',
                'purchase-orders.create',
                'purchase-orders.update',
                'purchase-orders.approve',
                'purchase-orders.cancel',
                'goods-receipts.view',
                'goods-receipts.create',
                'goods-receipts.update',
            ],
            'accountant' => [
                'invoices.view',
                'invoices.create',
                'invoices.update',
                'payments.view',
                'payments.create',
                'billings.view',
                'billings.create',
                'billings.update',
                'billings.mark-paid',
                'billings.mark-failed',
                'billings.cancel',
                'billings.refund',
                'accounting.view',
                'accounting.create',
                'accounting.update',
                'accounting.delete',
                'accounting.post',
                'accounting.cancel',
                'reports.view',
                'reports.export',
                'analytics.view',
            ],
            'technician' => [
                'tickets.view',
                'tickets.update',
                'tickets.close',
                'diagnostics.view',
                'diagnostics.create',
                'diagnostics.update',
                'diagnostics.start',
                'diagnostics.complete',
                'diagnostics.cancel',
                'repairs.view',
                'repairs.create',
                'repairs.update',
                'repairs.start',
                'repairs.complete',
                'quotes.view',
                'quotes.create',
                'quotes.update',
                'devices.view',
                'customers.view',
                'warranties.view',
                'warranties.claim',
                'work-orders.view',
                'ai.view',
                'ai.use',
            ],
            'customer' => [
                'customer.portal.view',
                'customer.portal.tickets.view',
                'customer.portal.invoices.view',
                'customer.portal.pay',
                'customer.portal.marketplace.view',
            ],
        ];

        foreach ($rolePermissions as $roleName => $permissions) {
            $role = Role::query()->firstOrCreate([
                'name' => $roleName,
                'guard_name' => 'web',
            ]);

            $resolvedPermissions = collect($permissions)
                ->map(static fn (string $permissionName): Permission => Permission::query()->firstOrCreate([
                    'name' => $permissionName,
                    'guard_name' => 'web',
                ]))
                ->all();

            $role->syncPermissions($resolvedPermissions);
        }
    }
}
