<?php

declare(strict_types=1);

return [
    'required_files' => [
        'README.md',
        '.env.example',
        'Dockerfile',
        'docker-compose.yml',
        'docker/observability/prometheus/prometheus.yml',
        'docker/observability/prometheus/rules/iatechs-slo.rules.yml',
        'docker/observability/alertmanager/alertmanager.yml',
        'docker/observability/grafana/provisioning/datasources/prometheus.yml',
        'docker/observability/grafana/provisioning/dashboards/dashboards.yml',
        'docker/observability/grafana/dashboards/iatechs-observability.json',
        'config/app.php',
        'config/database.php',
        'config/broadcasting.php',
        'config/cors.php',
        'config/security.php',
        'config/queue.php',
        'config/services.php',
        'deploy/one-file-production.sh',
        'deploy/observability-postdeploy-check.sh',
        '.github/workflows/security.yml',
        'docs/operations/11-Production-Env-Contract.md',
        'docs/operations/22-Architecture-Audit-Runbook.md',
        'docs/operations/24-Realtime-Broadcast-Runbook.md',
        'docs/operations/25-Observability-Prometheus-Grafana-Runbook.md',
        'docs/operations/26-Security-Scanning-Runbook.md',
    ],

    'required_composer_scripts' => [
        'analyse',
        'test',
        'test:arch',
        'audit:architecture',
        'validate:testing',
    ],

    'required_env_keys' => [
        'APP_NAME',
        'APP_ENV',
        'APP_KEY',
        'APP_DEBUG',
        'APP_URL',
        'LOG_CHANNEL',
        'LOG_LEVEL',
        'DB_CONNECTION',
        'DB_HOST',
        'DB_PORT',
        'DB_DATABASE',
        'DB_USERNAME',
        'DB_PASSWORD',
        'REDIS_CLIENT',
        'REDIS_HOST',
        'REDIS_PORT',
        'REDIS_PASSWORD',
        'CACHE_STORE',
        'SESSION_DRIVER',
        'SESSION_SECURE_COOKIE',
        'SESSION_HTTP_ONLY',
        'SESSION_SAME_SITE',
        'QUEUE_CONNECTION',
        'CORS_ALLOWED_ORIGINS',
        'CORS_SUPPORTS_CREDENTIALS',
        'SECURITY_HSTS_ENABLED',
        'OBS_PAYMENT_SUCCESS_RATE_MIN',
        'OBS_PAYMENT_FAILED_24H_ALERT',
        'OBS_PENDING_ONLINE_STALE_MINUTES',
        'OBS_PENDING_ONLINE_ALERT',
        'OBS_SUBS_PAST_DUE_ALERT',
        'OBS_SUBS_CHURN_30D_MAX',
        'OBS_EXPORTER_ENABLED',
        'OBS_EXPORTER_TOKEN',
        'OBS_EXPORTER_ALLOWED_IPS',
        'OBS_ALERTS_ENABLED',
        'OBS_ALERTS_EMAIL_ENABLED',
        'OBS_ALERTS_EMAIL_RECIPIENTS',
        'OBS_ALERTS_SLACK_ENABLED',
        'OBS_ALERTS_SLACK_WEBHOOK_URL',
        'OBS_ALERTS_COOLDOWN_MINUTES',
        'OBS_ALERTS_CHECK_INTERVAL_MINUTES',
        'OBS_EXPORTER_TOKEN_FILE',
        'OBS_ALERTS_SLACK_WEBHOOK_FILE',
        'PROMETHEUS_RETENTION_TIME',
        'GRAFANA_ADMIN_USER',
        'GRAFANA_ADMIN_PASSWORD',
        'BROADCAST_CONNECTION',
        'FILESYSTEM_DISK',
        'AWS_ACCESS_KEY_ID',
        'AWS_SECRET_ACCESS_KEY',
        'AWS_DEFAULT_REGION',
        'AWS_BUCKET',
        'MAIL_MAILER',
        'MAIL_MAILER_TRANSACTIONAL',
        'TRANSACTIONAL_EMAIL_PROVIDER',
        'MAIL_FROM_ADDRESS',
        'MAIL_FROM_NAME',
        'SANCTUM_STATEFUL_DOMAINS',
        'AZURE_OPENAI_RESPONSES_ENDPOINT',
        'AZURE_OPENAI_API_KEY',
        'VITE_BROADCAST_CONNECTION',
        'VITE_REVERB_APP_KEY',
        'VITE_REVERB_HOST',
        'VITE_REVERB_PORT',
        'VITE_REVERB_SCHEME',
        'VITE_PUSHER_APP_KEY',
        'VITE_PUSHER_HOST',
        'VITE_PUSHER_PORT',
        'VITE_PUSHER_SCHEME',
        'VITE_PUSHER_APP_CLUSTER',
    ],

    'required_env_values' => [
        'APP_ENV' => 'production',
        'APP_DEBUG' => 'false',
        'DB_CONNECTION' => 'pgsql',
        'CACHE_STORE' => 'redis',
        'SESSION_DRIVER' => 'redis',
        'QUEUE_CONNECTION' => 'redis',
        'BROADCAST_CONNECTION' => 'reverb',
    ],

    'integration_env_matrix' => [
        'azure_openai' => [
            'required' => true,
            'keys' => [
                'AZURE_OPENAI_RESPONSES_ENDPOINT',
                'AZURE_OPENAI_API_KEY',
            ],
        ],
        'redis_queue_horizon' => [
            'required' => true,
            'keys' => [
                'REDIS_HOST',
                'REDIS_PORT',
                'QUEUE_CONNECTION',
                'HORIZON_PREFIX',
            ],
        ],
        'mail' => [
            'required' => true,
            'keys' => [
                'MAIL_MAILER',
                'MAIL_MAILER_TRANSACTIONAL',
                'TRANSACTIONAL_EMAIL_PROVIDER',
                'MAIL_FROM_ADDRESS',
                'MAIL_FROM_NAME',
            ],
        ],
        'storage_s3' => [
            'required' => true,
            'keys' => [
                'FILESYSTEM_DISK',
                'AWS_ACCESS_KEY_ID',
                'AWS_SECRET_ACCESS_KEY',
                'AWS_DEFAULT_REGION',
                'AWS_BUCKET',
            ],
        ],
        'websockets_reverb' => [
            'required' => true,
            'keys' => [
                'BROADCAST_CONNECTION',
                'REVERB_APP_ID',
                'REVERB_APP_KEY',
                'REVERB_APP_SECRET',
                'REVERB_HOST',
                'REVERB_PORT',
                'REVERB_SCHEME',
                'VITE_BROADCAST_CONNECTION',
                'VITE_REVERB_APP_KEY',
                'VITE_REVERB_HOST',
                'VITE_REVERB_PORT',
                'VITE_REVERB_SCHEME',
            ],
        ],
        'pusher' => [
            'required' => false,
            'keys' => [
                'PUSHER_APP_ID',
                'PUSHER_APP_KEY',
                'PUSHER_APP_SECRET',
                'PUSHER_APP_CLUSTER',
            ],
        ],
        'mercado_pago' => [
            'required' => false,
            'keys' => [
                'MERCADOPAGO_ACCESS_TOKEN',
                'MERCADOPAGO_PUBLIC_KEY',
                'MERCADOPAGO_CURRENCY',
            ],
        ],
        'stripe' => [
            'required' => false,
            'keys' => [
                'STRIPE_KEY',
                'STRIPE_SECRET',
                'STRIPE_WEBHOOK_SECRET',
            ],
        ],
        'cloudflare' => [
            'required' => false,
            'keys' => [
                'CLOUDFLARE_API_TOKEN',
                'CLOUDFLARE_ZONE_ID',
            ],
        ],
        'observability_exporter' => [
            'required' => true,
            'keys' => [
                'OBS_EXPORTER_ENABLED',
                'OBS_EXPORTER_TOKEN',
                'OBS_EXPORTER_ALLOWED_IPS',
            ],
        ],
        'observability_alerting' => [
            'required' => true,
            'keys' => [
                'OBS_ALERTS_ENABLED',
                'OBS_ALERTS_EMAIL_ENABLED',
                'OBS_ALERTS_EMAIL_RECIPIENTS',
                'OBS_ALERTS_SLACK_ENABLED',
                'OBS_ALERTS_SLACK_WEBHOOK_URL',
                'OBS_ALERTS_COOLDOWN_MINUTES',
                'OBS_ALERTS_CHECK_INTERVAL_MINUTES',
            ],
        ],
        'prometheus_grafana' => [
            'required' => false,
            'keys' => [
                'OBS_EXPORTER_TOKEN_FILE',
                'OBS_ALERTS_SLACK_WEBHOOK_FILE',
                'PROMETHEUS_RETENTION_TIME',
                'GRAFANA_ADMIN_USER',
                'GRAFANA_ADMIN_PASSWORD',
            ],
        ],
        'oauth_jwt_passport' => [
            'required' => false,
            'keys' => [
                'OAUTH_CLIENT_ID',
                'OAUTH_CLIENT_SECRET',
                'JWT_SECRET',
                'PASSPORT_CLIENT_ID',
                'PASSPORT_CLIENT_SECRET',
            ],
        ],
        'oauth_social' => [
            'required' => false,
            'keys' => [
                'GOOGLE_CLIENT_ID',
                'GOOGLE_CLIENT_SECRET',
                'GOOGLE_REDIRECT_URI',
                'GITHUB_CLIENT_ID',
                'GITHUB_CLIENT_SECRET',
                'GITHUB_REDIRECT_URI',
                'MICROSOFT_CLIENT_ID',
                'MICROSOFT_CLIENT_SECRET',
                'MICROSOFT_REDIRECT_URI',
                'MICROSOFT_TENANT',
            ],
        ],
    ],
];
